services:
  - type: web
    name: aplicativo-de-requerimento-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/public/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: MAIL_HOST
        value: smtp-relay.brevo.com
      - key: MAIL_PORT
        value: "465"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: STORAGE_ENDPOINT
        sync: false
      - key: STORAGE_REGION
        sync: false
      - key: STORAGE_ACCESS_KEY_ID
        sync: false
      - key: STORAGE_SECRET_ACCESS_KEY
        sync: false
      - key: STORAGE_BUCKET_NAME
        sync: false
      - key: STORAGE_PUBLIC_URL
        sync: false
      - key: APP_MASTER_EMAIL
        sync: false
      - key: APP_MASTER_PASSWORD
        sync: false
